### ISSUE TITLE
useGlobalState Discussion

### ISSUE THREAD

**Issue by r17x** [evilfactorylabs/useGlobalState#1]
Project Name: `useGlobalState`
Release Package: `@evilfactorylabs/use-global-state`

Project Structure:
```
- root
-- src
--- index.js
-- dist|lib ❓
--- index|useGlobalState.js ❓
-- package.json
```

# Todo
- [x] Add `main library` at `src/index.js`. #2 https://github.com/evilfactorylabs/useGlobalState/pull/2 [Need Review] @ri7nz
- [x] Add Test. #4 
- [x] Add `README.md`. https://github.com/evilfactorylabs/useGlobalState/pull/2 [Need Review] @ri7nz
- [x] Add `Examples` at `examples`. 
(Create a Project for test, like codesandbox or your own github repository)
- [ ] Release & Distribution. #3
